# Generated by Django 4.2 on 2023-05-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinList',
            fields=[
                ('coin_pk', models.AutoField(primary_key=True, serialize=False)),
                ('coin_id', models.CharField(max_length=20)),
                ('coin_amnt', models.BigIntegerField()),
            ],
            options={
                'db_table': 'coin_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewAccount',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'new_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TradeList',
            fields=[
                ('user_pk', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('coin_pk', models.CharField(max_length=8)),
                ('tlog_cont_time', models.IntegerField(blank=True, null=True)),
                ('tlog_cont_type', models.CharField(max_length=2)),
                ('tlog_coin_amnt', models.BigIntegerField()),
                ('tlog_trade_price', models.IntegerField()),
                ('tlog_total_price', models.BigIntegerField()),
                ('tlog_charge', models.IntegerField()),
                ('tlog_earn_rate', models.IntegerField(blank=True, null=True)),
                ('tlog_order_time', models.IntegerField()),
            ],
            options={
                'db_table': 'trade_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('user_pk', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=40)),
                ('user_pw', models.CharField(max_length=40)),
                ('user_pn', models.CharField(max_length=40)),
                ('user_em', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'user_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WalletList',
            fields=[
                ('user_pk', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('coin_pk', models.CharField(max_length=8)),
                ('wallet_addr', models.CharField(max_length=16)),
                ('wallet_coin_amnt', models.BigIntegerField()),
                ('wallet_aver_price', models.IntegerField()),
            ],
            options={
                'db_table': 'wallet_list',
                'managed': False,
            },
        ),
    ]
